<center>
<h2>Lecture 01<br>Introduction to NumPy</h2>
<br>
Computational Vision<br>
August 31, 2017
</center>


### Overview of the Basics
See the Piazza resources page for links to tutorials
+ A first example
+ Array creation
+ Array dimensions
+ Changing shape
+ Indexing and slicing
+ Views and copying
+ Arithmetic operators
+ Universal functions
+ Concatenating and splitting
+ Summary of differences between NumPy arrays and Python lists

The code written during class will be posted both as an html file and as a Jupyter notebook.

### A first example
We'll start with an example showing
+ Initial creation
+ Reshaping from one dimension to two
+ Indexing to access and change values
+ Single data type:  dtype
+ The type of the array object

In [1]:
import numpy as np     # standard convention
# We will fill in here during lecture

a = np.array( [ 4, 2, 6, 19, 24, 13])
# print(a)
a.shape = (3,2)
print(a)
b = a.reshape(6)
print(b)
print(b.shape)
b[3] = 999
print(b)
print(a)
print(a.dtype)
print(type(a))



[[ 4  2]
 [ 6 19]
 [24 13]]
[ 4  2  6 19 24 13]
(6,)
[  4   2   6 999  24  13]
[[  4   2]
 [  6 999]
 [ 24  13]]
int64
<class 'numpy.ndarray'>


### Array creation
Many methods to explore:
+ Creating directly from a list or from lists of lists
+ arange
+ linspace
+ random
+ eye
+ ones
+ zeros
+ setting the data type


In [2]:
# Example code on array creation inserted during lecture
a = np.arange( 10 ).reshape( (2,5))
print(a)
b = np.linspace( -1, 1, num=40, endpoint=True).reshape( (4,10))
print(b)
print(b.dtype)
c = np.random.random( (3,5))
print(c)
d = np.eye( 4 )
print(d)
e = np.eye( 5,3, k=-1, dtype=np.int64)
print(e)
print(e.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[-1.         -0.94871795 -0.8974359  -0.84615385 -0.79487179 -0.74358974
  -0.69230769 -0.64102564 -0.58974359 -0.53846154]
 [-0.48717949 -0.43589744 -0.38461538 -0.33333333 -0.28205128 -0.23076923
  -0.17948718 -0.12820513 -0.07692308 -0.02564103]
 [ 0.02564103  0.07692308  0.12820513  0.17948718  0.23076923  0.28205128
   0.33333333  0.38461538  0.43589744  0.48717949]
 [ 0.53846154  0.58974359  0.64102564  0.69230769  0.74358974  0.79487179
   0.84615385  0.8974359   0.94871795  1.        ]]
float64
[[ 0.61506442  0.04142655  0.47009712  0.46000103  0.47136998]
 [ 0.59532324  0.6116961   0.32911458  0.29530243  0.60263806]
 [ 0.14195212  0.54314107  0.46296105  0.63979221  0.16001589]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]
int64


### Array dimensions
+ 1-d: a row vector
+ 2-d: a traditional array with rows indexed first and columns indexed second
+ n-d: nested dimesions read from outside in
+ Can even have 0-d, which is essentially a scalar, but we will not spend any time on this



In [3]:
# Example code and printing illustrating different dimensions
a = np.arange(24)
print(a)
b = a.reshape( (3,8))
print(b)
c = b.reshape( (4,2,3))
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


### Shapes and reshaping
+ We can reshape a NumPy array to any other shape that uses the same number of values
+ The shape may be assigned as an l-value and accessed as an r-value
    + It is simply an attribute of each NumPy array
+ ravel and flatten create 1d versions of arrays
    + ravel creates a shallow copy, while flatten creates a deep copy.

In [4]:
# Example reshaping code
a = np.random.random( (3,5))*10
print(a)
a.shape = (5,3)
print(a)
b = a.ravel()   # view
print(b)
c = a.flatten()   # deep copy
print(c)
b[4] = 89
print('-----\nAfter changing b')
print(a)
print(b)
print(c)

[[ 8.93230645  8.11029738  9.45812643  3.15177358  9.6279907 ]
 [ 5.8608416   8.89546046  3.57936742  9.24577021  7.03872852]
 [ 6.44495464  5.85902616  0.7750753   5.16573323  1.93268212]]
[[ 8.93230645  8.11029738  9.45812643]
 [ 3.15177358  9.6279907   5.8608416 ]
 [ 8.89546046  3.57936742  9.24577021]
 [ 7.03872852  6.44495464  5.85902616]
 [ 0.7750753   5.16573323  1.93268212]]
[ 8.93230645  8.11029738  9.45812643  3.15177358  9.6279907   5.8608416
  8.89546046  3.57936742  9.24577021  7.03872852  6.44495464  5.85902616
  0.7750753   5.16573323  1.93268212]
[ 8.93230645  8.11029738  9.45812643  3.15177358  9.6279907   5.8608416
  8.89546046  3.57936742  9.24577021  7.03872852  6.44495464  5.85902616
  0.7750753   5.16573323  1.93268212]
-----
After changing b
[[  8.93230645   8.11029738   9.45812643]
 [  3.15177358  89.           5.8608416 ]
 [  8.89546046   3.57936742   9.24577021]
 [  7.03872852   6.44495464   5.85902616]
 [  0.7750753    5.16573323   1.93268212]]
[  8.93230645 

### Indexing and slicing
+ Initial intuitions are similar to operations on Python lists
    + Watch out though for important differences that will emerge, starting with syntax
+ 1d, 2d, and more
+ Leaving out a dimension (at the end) gives the entire contents of that dimension

In [5]:
# Example slicing code
a = np.arange( 20 ).reshape( (4,5))
print(a)
print(a[2:4,:3])
print(a[::2,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[10 11 12]
 [15 16 17]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]


### Views and copying
+ Unlike lists, when an array is sliced, the result is a view or shallow copy of the array.
+ When the slice is an l-value, the contents of the array are changed!
    + We will use this next week to insert a picture within a picture

In [6]:
# Example views and copies
print(a[::2, 1::2 ].shape)
print(a)
a[::2, 1::2 ] = np.array( [[99,98],[97,96]])
print(a)

(2, 2)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0 99  2 98  4]
 [ 5  6  7  8  9]
 [10 97 12 96 14]
 [15 16 17 18 19]]


### Arithmetic operators applied to arrays
+ Addition, subtraction, multiplication, etc.
    + Note that multiplication is component-wise rather than true matrix multiplication
+ Operators require compatible dimensions.  For example
    + A scalar is compatible with any array
    + Arrays of the same dimensions are compatible 
+ More generally, compatibility is defined via broadcasting rules, which we will study in Lecture 2

In [7]:
# Example use of arithmetic operators
x = np.arange( 12 ).reshape( (3,4))
y = np.arange( 20, 32).reshape( (3,4))
print(x)
print(y)
print(x+y)
print(3*x)
print(3+x)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [8]:
# Broadcasting
a = np.arange( 10,14)
print(a.shape)
print(a+x)  # ?
b = np.arange( 10,13 )
print(b.shape)
# print(b+x)  # incompatible shapes
b = b.reshape( (3,1))
print(b.shape)
print(x+b)

(4,)
[[10 12 14 16]
 [14 16 18 20]
 [18 20 22 24]]
(3,)
(3, 1)
[[10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]


In [9]:
# Try adding 3x2 to 3x4 to see...
c = np.arange( -10, -4 ).reshape( (3,2))
print(c.shape)
print(c)
# print(x+c)

(3, 2)
[[-10  -9]
 [ -8  -7]
 [ -6  -5]]


In [10]:
# 
g = np.arange( 0,16).reshape( (4,4))
h = np.arange( 10, 14).reshape( (4,1))
i = np.arange( 20, 24).reshape( (1,4))
print(g+h)
print(g+i)
print(h+i)

[[10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]
 [25 26 27 28]]
[[20 22 24 26]
 [24 26 28 30]
 [28 30 32 34]
 [32 34 36 38]]
[[30 31 32 33]
 [31 32 33 34]
 [32 33 34 35]
 [33 34 35 36]]


### Universal functions - Applied to entire array
+ We'll look at just a few important examples (of many):
    + Average, dot, max, sum, cumsum
+ Can specify the axis along which the function is applied
+ Some functions, like argmax, give results that are defined in terms of the 1d, raveled version of the array!

In [11]:
# Many examples of universal functions
a = np.random.random( (3,3))
print(a)
print('average = ', np.average(a))
print('cumsum (reshaped) = ', np.cumsum(a).reshape( a.shape))

[[ 0.93425291  0.34196458  0.96854341]
 [ 0.33357283  0.59166344  0.70130446]
 [ 0.80081765  0.68082358  0.18546946]]
average =  0.615379146392
cumsum (reshaped) =  [[ 0.93425291  1.27621749  2.2447609 ]
 [ 2.57833373  3.16999717  3.87130162]
 [ 4.67211927  5.35294285  5.53841232]]


In [12]:
# Cumsum along the axis
a = np.random.random( (4,3))*10
a = a.astype(int)
print(a)
print(np.cumsum(a,axis=1))
i = a.argmax()
print('ravel max index: ', i)
print('incoordinates: ', np.unravel_index(i,a.shape))

[[9 2 0]
 [3 0 0]
 [7 9 8]
 [8 0 0]]
[[ 9 11 11]
 [ 3  3  3]
 [ 7 16 24]
 [ 8  8  8]]
ravel max index:  0
incoordinates:  (0, 0)


### Combining and splitting arrays
+ concatenate:
    + Give tuple of arrays and specify axis along which to combine
    + Arrays dimensions must match exactly except along the axis
+ Split using indices
+ We'll look at example of combining 2d arrays into another 2d array, but also extending to 3d
    + Useful for splitting and combining images

In [13]:
# Initial example for concatenation and splitting
a = np.arange( 12).reshape( (3,4))
b = np.arange( 20,32).reshape( (3,4))
print( np.concatenate( (a,b)))
print( np.concatenate( (a,b), axis=1))
a3 = a[:,:,np.newaxis]
print('after adding a new axis a3.shape = ', a3.shape)
b3 = b[:,:,np.newaxis]
c = np.concatenate( (a3,b3), axis=-1)
print(c.shape)
print(c)
a1 = c[:,:,0]
b1 = c[:,:,1]
print(a1.shape)
print(b1.shape)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3 20 21 22 23]
 [ 4  5  6  7 24 25 26 27]
 [ 8  9 10 11 28 29 30 31]]
after adding a new axis a3.shape =  (3, 4, 1)
(3, 4, 2)
[[[ 0 20]
  [ 1 21]
  [ 2 22]
  [ 3 23]]

 [[ 4 24]
  [ 5 25]
  [ 6 26]
  [ 7 27]]

 [[ 8 28]
  [ 9 29]
  [10 30]
  [11 31]]]
(3, 4)
(3, 4)


### NumPy arrays vs. Python lists, revisited
+ NumPy lists are homogeneous; Python lists are heterogeneous
+ Slicing a NumPy list creates a view without copying; slicing a Python lists creates a new list
+ Many functional and numeric operations have been created for NumPy arrays